name: Hardcore
version: 1.5.1
author: Jakura
main: de.Jakura.Hardcore.Main.main
website: https://github.com/Jakura/Hardcore
api-version: 1.16

commands:
     elbuy:
          description: Kaufe dir mit dias Extra Leben
     elshop:
          description: Kaufe dir mit dias Extra Leben
